services:
  web-1:
    image: yuradotnet/flask-demo
    ports:
      - "5000:5000"
    depends_on:
      - db

  db:
    image: postgres:15
    env_file: db.env
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
